### ISSUE TITLE
switch video track and cache in the scale

### ISSUE THREAD

**Issue by candrapersada** [maoiscat/mpv-osc-framework#1]
why isn't there a video track switch in the oscf? and show cache in the scale

**Comment by maoiscat** [comment]
oscf dosen't need some ''video track switch'' to run itself.

if you need it, please do it yourself.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/15/2023 02:32 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-framework] switch video track (Issue #1) |

why isn't there a video track switch in the oscf?
