### ISSUE TITLE
Module import error when using "require 'module'" 

### ISSUE THREAD

**Issue by ghost** [maoiscat/mpv-osc-framework#2]
I have just tested this.  I'm not well-versed in LUA, but when I first tried to launch mpv with the demo osc per the instructions, I received these errors:

```
$ mpv test-file.mp4 

[expansion] 
[expansion] stack traceback:
[expansion] 	/home/me/.config/mpv/scripts/expansion.lua:6: in main chunk
[expansion] 	[C]: at 0x56299274b590
[expansion] 	[C]: at 0x56299274ba50
[expansion] Lua error: /home/me/.config/mpv/scripts/expansion.lua:6: module 'oscf' not found:
[expansion] 	no field package.preload['oscf']
[expansion] 	no file '/usr/share/luajit-2.1.0-beta3/oscf.lua'
[expansion] 	no file '/usr/local/share/lua/5.1/oscf.lua'
[expansion] 	no file '/usr/local/share/lua/5.1/oscf/init.lua'
[expansion] 	no file '/usr/share/lua/5.1/oscf.lua'
[expansion] 	no file '/usr/share/lua/5.1/oscf/init.lua'
[expansion] 	no file '/usr/local/lib/lua/5.1/oscf.so'
[expansion] 	no file '/usr/lib/lua/5.1/oscf.so'
[expansion] 	no file '/usr/local/lib/lua/5.1/loadall.so'
[main] 
[main] stack traceback:
[main] 	/home/me/.config/mpv/scripts/main.lua:4: in main chunk
[main] 	[C]: at 0x56299274b590
[main] 	[C]: at 0x56299274ba50
[main] Lua error: /home/me/.config/mpv/scripts/main.lua:4: module 'expansion' not found:
[main] 	no field package.preload['expansion']
[main] 	no file '/usr/share/luajit-2.1.0-beta3/expansion.lua'
[main] 	no file '/usr/local/share/lua/5.1/expansion.lua'
[main] 	no file '/usr/local/share/lua/5.1/expansion/init.lua'
[main] 	no file '/usr/share/lua/5.1/expansion.lua'
[main] 	no file '/usr/share/lua/5.1/expansion/init.lua'
[main] 	no file '/usr/local/lib/lua/5.1/expansion.so'
[main] 	no file '/usr/lib/lua/5.1/expansion.so'
[main] 	no file '/usr/local/lib/lua/5.1/loadall.so'
```

To fix the problem, I have replaced (in _expansion.lua_) `require 'oscf'` with `dofile'oscf.lua'`, and replaced (in _main.lua_) `require 'expansion'` with `dofile'expansion.lua'`.

I believe this most likely has to do with LUA path configurations on the user's system, so I don't think your demo instructions on the README will work for all users.    

I don't know what the correct solution is, I am only alerting you to the issue.  It may just require an additional note on the README about module paths.

Thank you for your work

**Comment by maoiscat** [comment]
read the ''getting startrd'' section again

1. Make a new folder in "~~/mpv/scripts/", such as "~~/mpv/scripts/demo/"



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/13/2023 05:53 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-framework] Module import error when using "require 'module'" (Issue #2) |

I have just tested this. I'm not well-versed in LUA, but when I first tried to launch mpv with the demo osc per the instructions, I received these errors:

$ mpv test-file.mp4 

[expansion] 
[expansion] stack traceback:
[expansion] 	/home/me/.config/mpv/scripts/expansion.lua:6: in main chunk
[expansion] 	[C]: at 0x56299274b590
[expansion] 	[C]: at 0x56299274ba50
[expansion] Lua error: /home/me/.config/mpv/scripts/expansion.lua:6: module 'oscf' not found:
[expansion] 	no field package.preload['oscf']
[expansion] 	no file '/usr/share/luajit-2.1.0-beta3/oscf.lua'
[expansion] 	no file '/usr/local/share/lua/5.1/oscf.lua'
[expansion] 	no file '/usr/local/share/lua/5.1/oscf/init.lua'
[expansion] 	no file '/usr/share/lua/5.1/oscf.lua'
[expansion] 	no file '/usr/share/lua/5.1/oscf/init.lua'
[expansion] 	no file '/usr/local/lib/lua/5.1/oscf.so'
[expansion] 	no file '/usr/lib/lua/5.1/oscf.so'
[expansion] 	no file '/usr/local/lib/lua/5.1/loadall.so'
[main] 
[main] stack traceback:
[main] 	/home/me/.config/mpv/scripts/main.lua:4: in main chunk
[main] 	[C]: at 0x56299274b590
[main] 	[C]: at 0x56299274ba50
[main] Lua error: /home/me/.config/mpv/scripts/main.lua:4: module 'expansion' not found:
[main] 	no field package.preload['expansion']
[main] 	no file '/usr/share/luajit-2.1.0-beta3/expansion.lua'
[main] 	no file '/usr/local/share/lua/5.1/expansion.lua'
[main] 	no file '/usr/local/share/lua/5.1/expansion/init.lua'
[main] 	no file '/usr/share/lua/5.1/expansion.lua'
[main] 	no file '/usr/share/lua/5.1/expansion/init.lua'
[main] 	no file '/usr/local/lib/lua/5.1/expansion.so'
[main] 	no file '/usr/lib/lua/5.1/expansion.so'
[main] 	no file '/usr/local/lib/lua/5.1/loadall.so'


To fix the problem, I have replaced (in expansion.lua) require 'oscf' with dofile'oscf.lua', and replaced (in main.lua) require 'expansion' with dofile'expansion.lua'.

I believe this most likely has to do with LUA path configurations on the user's system, so I don't think your demo instructions on the README will work for all users.

I don't know what the correct solution is, I am only alerting you to the issue. It may just require an additional note on the README about module paths.

Thank you for your work
