### ISSUE TITLE
Playback brightness in osc

### ISSUE THREAD

**Issue by Mint-me123** [maoiscat/mpv-osc-framework#3]
Can playback brightness be added to the osc in any way? I have trawled around wwwwwww but it seems that it is not a very (or at all) requested feature or it is not possible and everyone (except me) knows that. I am using MPV on a linux tablet without a keyboard only controlling mpv with the osc and a mouse so keyboard shortcuts is not really what i am looking for.

**Comment by maoiscat** [comment]
you need to make a custom button, which execute the command mp.commandv('add', 'brightness', '+5') or mp.commandv('add', 'brightness', '-5') when pressed.

Anyway you will always need a keyboard.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/20/2023 14:49 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-framework] Playback brightness in osc (Issue #3) |

Can playback brightness be added to the osc in any way? I have trawled around wwwwwww but it seems that it is not a very (or at all) requested feature or it is not possible and everyone (except me) knows that. I am using MPV on a linux tablet without a keyboard only controlling mpv with the osc and a mouse so keyboard shortcuts is not really what i am looking for.

**Comment by Mint-me123** [comment]
I see. Thank you.
I made a workaround with the on screen keyboard in Linux. Then I don't need
a real keyboard and can change brightness with the mouse. Not "osc elegant"
but it works fine.
