### ISSUE TITLE
nothing can beat uosc though

### ISSUE THREAD

**Issue by aicynide** [maoiscat/mpv-osc-framework#4]

**Comment by maoiscat** [comment]
yes, it is you to beat uosc, because you are ''nothing''.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/28/2023 01:39 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-framework] nothing can beat uosc though (Issue #4) |
