### ISSUE TITLE
UI disappears when dragging subs

### ISSUE THREAD

**Issue by befabry** [maoiscat/mpv-osc-framework#5]
Hello,

The UI is disappearing when I drag subtitles over the "mpv-osc-modern" main.lua.

How can I fix it ? Is it a problem related to the config or something ?

**Comment by maoiscat** [comment]
need mote details, such as youdr console output



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/06/2023 06:19 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-framework] UI disappears when dragging subs (Issue #5) |

Hello,

The UI is disappearing when I drag subtitles over the "mpv-osc-modern" main.lua.

How can I fix it ? Is it a problem related to the config or something ?

**Comment by befabry** [comment]
Here is the output. Thanks a bunch

    Track added:
     (+) Video --vid=1 (*) (h264 1920x808 23.976fps)
     (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
     (+) Subs  --sid=1 'The%20Interview.1080p.BluRay.x264.YIFY.srt' (subrip) (external)
    [modern]
    [modern] stack traceback:
    [modern] 	/home/[username]/.config/mpv/scripts/modern/oscf.lua:357: in function 'dispatchEvent'
    [modern] 	/home/[username]/.config/mpv/scripts/modern/main.lua:140: in function 'prop'
    [modern] 	mp.defaults:407: in function 'handler'
    [modern] 	mp.defaults:510: in function 'call_event_handlers'
    [modern] 	mp.defaults:552: in function 'dispatch_events'
    [modern] 	mp.defaults:503: in function <mp.defaults:502>
    [modern] 	[C]: at 0x55ca37f1b5e0
    [modern] 	[C]: at 0x55ca37f1baa0
    [modern] Lua error: /home/[username]/.config/mpv/scripts/modern/main.lua:451: attempt to index a nil value

**Comment by maoiscat** [comment]
this is caused when adding a subtitle ''track'' during the playback, and this action is NOT recoganized as a ''file-load'' event in mpv.

i made a temporary fix, and you can download the latest main.lua to test it.

**Comment by befabry** [comment]
Hello,

I don't have access to my computer until the 14th may. I'll be sure to test
it and give you an update.

Thanks though

**Comment by befabry** [comment]
Hello,

it works perfectly !

Thanks a bunch :smile_cat:
